version: '3.8'

services:
  gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./gateway/docs.html:/usr/share/nginx/html/docs.html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./.dynamodb-data:/data
    user: root

  dynamodb-test:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-test
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    profiles:
      - test

  redis:
    image: redis:7-alpine
    container_name: redis-local
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:4.4
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs,s3
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:

