import { type Role, DataScope } from '@bitcrm/types';

export const DEFAULT_ROLES: Omit<Role, 'createdAt' | 'updatedAt'>[] = [
  {
    id: 'role-super-admin',
    name: 'Super Admin',
    description: 'Full system access with all permissions',
    permissions: {
      deals: { view: true, create: true, edit: true, delete: true },
      contacts: { view: true, create: true, edit: true, delete: true },
      companies: { view: true, create: true, edit: true, delete: true },
      products: { view: true, create: true, edit: true, delete: true },
      warehouses: { view: true, create: true, edit: true, delete: true },
      containers: { view: true, create: true, edit: true, delete: true },
      transfers: { view: true, create: true, edit: true, delete: true },
      users: { view: true, create: true, edit: true, delete: true },
      roles: { view: true, create: true, edit: true, delete: true },
      reports: { view: true, create: true, edit: true, delete: true },
      settings: { view: true, edit: true },
    },
    dataScope: {
      deals: DataScope.ALL,
      contacts: DataScope.ALL,
      companies: DataScope.ALL,
      products: DataScope.ALL,
      warehouses: DataScope.ALL,
      containers: DataScope.ALL,
      transfers: DataScope.ALL,
      users: DataScope.ALL,
      roles: DataScope.ALL,
      reports: DataScope.ALL,
      settings: DataScope.ALL,
    },
    dealStageTransitions: ['*->*'],
    isSystem: true,
    priority: 100,
  },
  {
    id: 'role-admin',
    name: 'Admin',
    description: 'Administrative access with most permissions',
    permissions: {
      deals: { view: true, create: true, edit: true, delete: true },
      contacts: { view: true, create: true, edit: true, delete: true },
      companies: { view: true, create: true, edit: true, delete: true },
      products: { view: true, create: true, edit: true, delete: false },
      warehouses: { view: true, create: true, edit: true, delete: false },
      containers: { view: true, create: true, edit: true, delete: false },
      transfers: { view: true, create: true, edit: true, delete: false },
      users: { view: true, create: true, edit: true, delete: true },
      roles: { view: true, create: false, edit: false, delete: false },
      reports: { view: true, create: true, edit: true, delete: false },
      settings: { view: true, edit: true },
    },
    dataScope: {
      deals: DataScope.ALL,
      contacts: DataScope.ALL,
      companies: DataScope.ALL,
      products: DataScope.ALL,
      warehouses: DataScope.ALL,
      containers: DataScope.ALL,
      transfers: DataScope.ALL,
      users: DataScope.ALL,
      roles: DataScope.ALL,
      reports: DataScope.ALL,
      settings: DataScope.ALL,
    },
    dealStageTransitions: ['*->*'],
    isSystem: true,
    priority: 80,
  },
  {
    id: 'role-dispatcher',
    name: 'Dispatcher',
    description: 'Manages deals and contacts within department',
    permissions: {
      deals: { view: true, create: true, edit: true, delete: false },
      contacts: { view: true, create: true, edit: true, delete: false },
      companies: { view: true, create: false, edit: false, delete: false },
      products: { view: true, create: false, edit: false, delete: false },
      warehouses: { view: true, create: false, edit: false, delete: false },
      containers: { view: true, create: false, edit: false, delete: false },
      transfers: { view: true, create: false, edit: false, delete: false },
      users: { view: true, create: false, edit: false, delete: false },
      roles: { view: true, create: false, edit: false, delete: false },
      reports: { view: true, create: false, edit: false, delete: false },
      settings: { view: true, edit: false },
    },
    dataScope: {
      deals: DataScope.DEPARTMENT,
      contacts: DataScope.DEPARTMENT,
      companies: DataScope.DEPARTMENT,
      products: DataScope.ALL,
      warehouses: DataScope.ALL,
      containers: DataScope.ALL,
      transfers: DataScope.DEPARTMENT,
      users: DataScope.DEPARTMENT,
      roles: DataScope.ALL,
      reports: DataScope.DEPARTMENT,
      settings: DataScope.ALL,
    },
    dealStageTransitions: [
      'new_lead->estimate_sent',
      'estimate_sent->approved',
      'approved->assigned',
      'new_lead->assigned',
      '*->canceled',
      '*->follow_up',
      '*->on_hold',
    ],
    isSystem: true,
    priority: 40,
  },
  {
    id: 'role-technician',
    name: 'Technician',
    description: 'Minimal access to assigned items only',
    permissions: {
      deals: { view: true, create: false, edit: true, delete: false },
      contacts: { view: true, create: false, edit: false, delete: false },
      companies: { view: true, create: false, edit: false, delete: false },
      products: { view: true, create: false, edit: false, delete: false },
      warehouses: { view: false, create: false, edit: false, delete: false },
      containers: { view: true, create: false, edit: false, delete: false },
      transfers: { view: true, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
      roles: { view: false, create: false, edit: false, delete: false },
      reports: { view: false, create: false, edit: false, delete: false },
      settings: { view: false, edit: false },
    },
    dataScope: {
      deals: DataScope.ASSIGNED_ONLY,
      contacts: DataScope.ASSIGNED_ONLY,
      companies: DataScope.ASSIGNED_ONLY,
      products: DataScope.ALL,
      warehouses: DataScope.ASSIGNED_ONLY,
      containers: DataScope.ASSIGNED_ONLY,
      transfers: DataScope.ASSIGNED_ONLY,
      users: DataScope.ASSIGNED_ONLY,
      roles: DataScope.ALL,
      reports: DataScope.ASSIGNED_ONLY,
      settings: DataScope.ALL,
    },
    dealStageTransitions: [
      'assigned->en_route',
      'en_route->on_site',
      'on_site->work_in_progress',
      'work_in_progress->pending_payment',
      'work_in_progress->pending_parts',
    ],
    isSystem: true,
    priority: 20,
  },
  {
    id: 'role-read-only',
    name: 'Read Only',
    description: 'View-only access to all resources',
    permissions: {
      deals: { view: true, create: false, edit: false, delete: false },
      contacts: { view: true, create: false, edit: false, delete: false },
      companies: { view: true, create: false, edit: false, delete: false },
      products: { view: true, create: false, edit: false, delete: false },
      warehouses: { view: true, create: false, edit: false, delete: false },
      containers: { view: true, create: false, edit: false, delete: false },
      transfers: { view: true, create: false, edit: false, delete: false },
      users: { view: true, create: false, edit: false, delete: false },
      roles: { view: true, create: false, edit: false, delete: false },
      reports: { view: true, create: false, edit: false, delete: false },
      settings: { view: true, edit: false },
    },
    dataScope: {
      deals: DataScope.ALL,
      contacts: DataScope.ALL,
      companies: DataScope.ALL,
      products: DataScope.ALL,
      warehouses: DataScope.ALL,
      containers: DataScope.ALL,
      transfers: DataScope.ALL,
      users: DataScope.ALL,
      roles: DataScope.ALL,
      reports: DataScope.ALL,
      settings: DataScope.ALL,
    },
    dealStageTransitions: [],
    isSystem: true,
    priority: 10,
  },
];
